use chrono::{DateTime, Utc};
use serenity::model::prelude::*;

use crate::state::Ticket;
use crate::tickets::types::find_type;
use crate::utils::format_duration;

/// Escape the 5 dangerous HTML chars. Order matters: & first.
pub fn escape_html(s: &str) -> String {
    s.replace('&', "&amp;")
        .replace('<', "&lt;")
        .replace('>', "&gt;")
        .replace('"', "&quot;")
        .replace('\'', "&#39;")
}

/// Build the full self-contained dark-mode HTML transcript.
pub fn build_transcription(
    ticket: &Ticket,
    messages: &[Message],
    reason: &str,
    closed_by: Option<UserId>,
    closed_at: DateTime<Utc>,
) -> String {
    let type_label = find_type(&ticket.type_id)
        .map(|t| t.button_label)
        .unwrap_or(&ticket.type_id);
    let duration = format_duration(closed_at.signed_duration_since(ticket.created_at));
    let claimed_label = ticket
        .claimed_by
        .map(|u| u.to_string())
        .unwrap_or_else(|| "—".to_string());
    let closed_by_label = closed_by
        .map(|u| u.to_string())
        .unwrap_or_else(|| "system".to_string());

    let cap = 2048 + messages.len().saturating_mul(512);
    let mut html = String::with_capacity(cap);

    html.push_str("<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n<meta charset=\"utf-8\">\n<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
    html.push_str(&format!(
        "<title>Transcript {} ({})</title>\n",
        escape_html(&ticket.id),
        escape_html(type_label)
    ));
    html.push_str(STYLE_CSS);
    html.push_str("</head>\n<body>\n<header class=\"meta\">\n<h1>Ticket Transcript</h1>\n");
    html.push_str(&meta_row("Ticket ID", &ticket.id));
    html.push_str(&meta_row("Type", type_label));
    html.push_str(&meta_row(
        "Owner",
        &format!("{} ({})", ticket.owner_name, ticket.owner_id),
    ));
    html.push_str(&meta_row("Claimed by", &claimed_label));
    html.push_str(&meta_row("Closed by", &closed_by_label));
    html.push_str(&meta_row("Reason", reason));
    html.push_str(&meta_row(
        "Created at",
        &ticket.created_at.format("%d/%m/%Y %H:%M:%S UTC").to_string(),
    ));
    html.push_str(&meta_row(
        "Closed at",
        &closed_at.format("%d/%m/%Y %H:%M:%S UTC").to_string(),
    ));
    html.push_str(&meta_row("Duration", &duration));
    html.push_str(&meta_row("Messages", &messages.len().to_string()));
    html.push_str("</header>\n");

    html.push_str("<section class=\"answers\">\n<h2>Form answers</h2>\n");
    if ticket.answers.is_empty() {
        html.push_str("<p class=\"empty\">No answers recorded.</p>\n");
    } else {
        html.push_str("<dl>\n");
        for (label, value) in &ticket.answers {
            let shown = if value.trim().is_empty() { "—" } else { value.as_str() };
            html.push_str(&format!(
                "<dt>{}</dt><dd>{}</dd>\n",
                escape_html(label),
                escape_html(shown)
            ));
        }
        html.push_str("</dl>\n");
    }
    html.push_str("</section>\n");

    html.push_str("<section class=\"messages\">\n<h2>Messages</h2>\n");
    if messages.is_empty() {
        html.push_str("<p class=\"empty\">No messages captured.</p>\n");
    } else {
        for m in messages {
            html.push_str(&render_message(m));
        }
    }
    html.push_str("</section>\n");
    html.push_str("<footer class=\"foot\">Generated by the ticket bot.</footer>\n");
    html.push_str("</body>\n</html>\n");
    html
}

fn meta_row(label: &str, value: &str) -> String {
    format!(
        "<div class=\"row\"><span class=\"k\">{}</span><span class=\"v\">{}</span></div>\n",
        escape_html(label),
        escape_html(value)
    )
}

fn render_message(m: &Message) -> String {
    let avatar = m
        .author
        .avatar
        .as_ref()
        .map(|hash| {
            format!(
                "https://cdn.discordapp.com/avatars/{}/{}.png?size=64",
                m.author.id, hash
            )
        })
        .unwrap_or_else(|| "https://cdn.discordapp.com/embed/avatars/0.png".to_string());
    let name = m
        .author
        .global_name
        .as_deref()
        .or(Some(m.author.username.as_str()))
        .unwrap_or("user");
    let ts = m.timestamp.format("%d/%m/%Y %H:%M:%S UTC").to_string();
    let body = if m.content.trim().is_empty() {
        "📎 (no text: attachment/embed)".to_string()
    } else {
        escape_html(&m.content).replace('\n', "<br>")
    };
    format!(
        "<article class=\"msg\">\n<div class=\"head\">\n<img class=\"avatar\" src=\"{avatar}\" alt=\"\" />\n<span class=\"author\">{author}</span>\n<span class=\"uid\">id {uid}</span>\n<time class=\"ts\">{ts}</time>\n</div>\n<div class=\"body\">{body}</div>\n</article>\n",
        avatar = escape_html(&avatar),
        author = escape_html(name),
        uid = escape_html(&m.author.id.to_string()),
        ts = escape_html(&ts),
        body = body,
    )
}

const STYLE_CSS: &str = r#"<style>
:root{color-scheme:dark}
*{box-sizing:border-box}
body{margin:0;padding:24px;background:#1e1f22;color:#dbdee1;font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,Arial,sans-serif;line-height:1.5;font-size:14px}
h1{font-size:20px;margin:0 0 16px;color:#f0b429}
h2{font-size:16px;margin:0 0 12px;color:#f0b429;border-bottom:1px solid #2b2d31;padding-bottom:6px}
header.meta,section.answers,section.messages{background:#2b2d31;border:1px solid #1e1f22;border-radius:8px;padding:16px;margin-bottom:16px}
.row{display:flex;gap:8px;padding:3px 0;border-bottom:1px dashed #313338}
.row:last-child{border-bottom:none}
.k{flex:0 0 180px;color:#949ba4;font-weight:600}
.v{flex:1;color:#dbdee1;word-break:break-word}
dl{margin:0;display:grid;grid-template-columns:1fr;gap:2px}
dt{color:#949ba4;font-weight:600;margin-top:8px}
dd{margin:2px 0 0 0;color:#dbdee1;word-break:break-word}
.empty{color:#949ba4;font-style:italic}
.msg{border-top:1px solid #1e1f22;padding:12px 0}
.msg:first-of-type{border-top:none}
.head{display:flex;align-items:center;gap:8px;flex-wrap:wrap;margin-bottom:6px}
.avatar{width:28px;height:28px;border-radius:50%;background:#313338}
.author{font-weight:700;color:#f2f3f5}
.uid{color:#949ba4;font-size:12px}
.ts{color:#949ba4;font-size:12px;margin-left:auto}
.body{color:#dbdee1;word-break:break-word}
footer.foot{color:#949ba4;font-size:12px;text-align:center;margin-top:8px}
</style>
"#;
